### ISSUE TITLE
difference between lastRawValue and lastFilteredValue

### ISSUE THREAD

**Issue by CatDroid** [casiez/OneEuroFilter#1]
In some implementations, I’ve noticed that the calculation of dvalue(speed) uses the original position from the previous time step, while others use the corrected position from the previous time step. 
Will this make a significant difference?

[OneEuroFilter.cpp](https://github.com/casiez/OneEuroFilter/blob/main/cpp/OneEuroFilter.cpp)

```
  // Fixed in 08/23 to use lastFilteredValue
  double dvalue = x->hasLastRawValue() ? (value - x->lastFilteredValue())*freq : 0.0 ; // FIXME: 0.0 or value?
```

**Comment by casiez** [comment]
From informal tests, using one of the other does not make a big difference but using the last filtered value looks like a bit better and also makes more sense.
